##########################################################################
#
#  Script:    Script for BRAIN (Basic Rnaseq Analysis IN) PBS
#  Author:    Maina Bitar
#  Created:   2020 at QIMR Berghofer (Brisbane, Australia)
#  Email:     Maina.Bitar@qimrberghofer.edu.au
#
##########################################################################
#PBS -N Rsem_002ab6fc-4846-41a0-8cf5-3109b2732799
#PBS -r n
#PBS -l mem=8GB,walltime=08:00:00,ncpus=8
#PBS -m ae

module load RSEM/1.3.1

rsem-calculate-expression --paired-end --bam --forward-prob 0 --no-bam-output -p 8 /working/lab_julietF/mainaB/ReMapTCGA/SamtoolsNovosort/002ab6fc-4846-41a0-8cf5-3109b2732799_110406_UNC13-SN749_0050_BB05L2ABXX.5.novosort.bam /working/lab_julietF/mainaB/ReMapTCGA/RsemIndex/RsemIndex /working/lab_julietF/mainaB/ReMapTCGA/RsemQuant/002ab6fc-4846-41a0-8cf5-3109b2732799_110406_UNC13-SN749_0050_BB05L2ABXX.5
